# Only build pushes for deployment branches
branches:
  only:
    - master
    - /^deploy.*$/

# We are Node/Javascript.
language: node_js

# We want node version
node_js:
    - "6.3.1"

# Cache Node Modules
cache:
  yarn: true
  directories:
    - node_modules
    - .happypack

# We don't need sudo
sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
    - pip install -r requirements.txt
